#!/usr/bin/env python3
"""Build the faithful transcript.tex from pass1/segment_*.json records.

Usage:
  build_transcript.py --paper-dir DIR

Output:
  <paper_dir>/transcript.tex  — self-contained document: \\input{preamble} + body
"""
import argparse
import json
import re
from pathlib import Path


def mmss(t: float) -> str:
    t = int(t)
    h, rem = divmod(t, 3600)
    m, s = divmod(rem, 60)
    return f"{h:d}:{m:02d}:{s:02d}" if h else f"{m:02d}:{s:02d}"


def latex_escape(s: str) -> str:
    """Minimal LaTeX escape for prose (not math)."""
    return (s.replace("\\", r"\textbackslash{}")
             .replace("&", r"\&")
             .replace("%", r"\%")
             .replace("$", r"\$")
             .replace("#", r"\#")
             .replace("_", r"\_")
             .replace("{", r"\{")
             .replace("}", r"\}")
             .replace("^", r"\^{}")
             .replace("~", r"\~{}"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--paper-dir", required=True)
    args = ap.parse_args()

    paper_dir = Path(args.paper_dir).resolve()
    pass1 = paper_dir / "pass1"
    out = paper_dir / "transcript.tex"

    records = []
    # Match only the unified per-segment records (segment_NNN.json with exactly
    # three digits and one dot before .json), not the transcript.json intermediates.
    for p in sorted(pass1.glob("segment_[0-9][0-9][0-9].json")):
        try:
            records.append(json.loads(p.read_text()))
        except Exception as e:
            print(f"[build_transcript] warning: failed to read {p}: {e}")
    if not records:
        print("[build_transcript] no segment_*.json found", file=__import__("sys").stderr)
        return

    lines = [
        r"\input{preamble}",
        r"\title{Faithful Transcript}",
        r"\author{Generated by video-to-latex}",
        r"\begin{document}",
        r"\maketitle",
        r"\tableofcontents",
        r"\clearpage",
        r"",
        r"\section*{Transcript}",
        r"",
    ]
    total_words = 0
    for rec in records:
        sid = rec.get("segment_id", "?")
        t0 = rec.get("t_start", 0.0)
        t1 = rec.get("t_end", 0.0)
        audio = rec.get("audio_transcript", "") or ""
        board = rec.get("board_tex", "") or ""
        hint = rec.get("section_hint", "")

        total_words += len(audio.split())

        title = f"Segment {sid} ({mmss(t0)}--{mmss(t1)})"
        if hint:
            title += f" --- {latex_escape(hint)}"
        lines.append(rf"\subsection*{{{title}}}")
        lines.append("")
        lines.append(r"\paragraph*{Audio:}")
        lines.append(latex_escape(audio) if audio else r"\emph{(no audio transcribed)}")
        lines.append("")
        lines.append(r"\paragraph*{Board:}")
        if board.strip():
            lines.append(r"\begin{verbatim}")
            # Redact triple-end-verbatim inside the content (vanishingly rare)
            lines.append(board.replace(r"\end{verbatim}", "[end-verbatim]"))
            lines.append(r"\end{verbatim}")
        else:
            lines.append(r"\emph{(empty board)}")
        lines.append("")

    lines.append(r"\end{document}")
    out.write_text("\n".join(lines))
    print(f"[build_transcript] wrote {out} with {len(records)} segments, "
          f"~{total_words} words of audio")


if __name__ == "__main__":
    main()
